name: Awesome Lint

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install awesome-lint CLI
        run: npm install -g awesome-lint

      - name: Run Awesome Lint
        run: awesome-lint
